// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6w29D2VVK4f-xuE3dFqrr3yFtKD4myA',
    appId: '1:671959676521:web:3cff328957a3026465d4f8',
    messagingSenderId: '671959676521',
    projectId: 'anak-mudah-papua',
    authDomain: 'anak-mudah-papua.firebaseapp.com',
    storageBucket: 'anak-mudah-papua.firebasestorage.app',
    measurementId: 'G-KFHHVMMJVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7OwRMZbu_NVhW6ISW35-qnGnAZEEeP4o',
    appId: '1:671959676521:android:817cfd98f179825a65d4f8',
    messagingSenderId: '671959676521',
    projectId: 'anak-mudah-papua',
    storageBucket: 'anak-mudah-papua.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6w29D2VVK4f-xuE3dFqrr3yFtKD4myA',
    appId: '1:671959676521:web:bacc1c3e356da9fd65d4f8',
    messagingSenderId: '671959676521',
    projectId: 'anak-mudah-papua',
    authDomain: 'anak-mudah-papua.firebaseapp.com',
    storageBucket: 'anak-mudah-papua.firebasestorage.app',
    measurementId: 'G-PV2X3CV7FB',
  );
}
